#!/usr/bin/env python
import roslib; roslib.load_manifest("airbus_demonstrator")
import rospy

import roslib.packages

from dynamic_graph_bridge.srv import *
from openhrp_bridge_msgs.srv import *
from std_srvs.srv import *

import time
import sys

rospy.init_node('launcher', log_level=rospy.DEBUG)

simulation = rospy.get_param('~simulation', False)

pkgLocation = roslib.packages.get_pkg_dir('airbus_demonstrator')
sotScriptsLocation = pkgLocation + "/src/"

def launchScript(code,title,description = ""):
    raw_input(title+':   '+description)
    rospy.loginfo(title)
    rospy.loginfo(code)
    for line in code:
        if line != '' and line[0] != '#':
            print line
            answer = runCommandClient(str(line))
            rospy.logdebug(answer)
            print answer
    rospy.loginfo("...done with "+title)

def startRealRobot():
    rospy.loginfo("restarting the controllers")
    rospy.wait_for_service("restart_controller")
    try:
        restartControllerClient = rospy.ServiceProxy('restart_controller',Empty)
        restartControllerClient()
    except:
        raw_input("Catch an error while starting the controller. Check if you want to continue.")
    rospy.loginfo("...restarting...")

    rospy.loginfo("waiting for switch_servo")
    rospy.wait_for_service("switch_servo")
    rospy.loginfo("...ok")

    rospy.loginfo("switching to servo on (can take time)")
    ok = False
    while not ok:
        try:
            switchServoClient = rospy.ServiceProxy('switch_servo', SwitchServo)
            answer = switchServoClient(True, "all")
            rospy.logdebug(answer)
            ok = True
        except:
            time.sleep(1)
            rospy.loginfo("...not ok, reconnecting ...")


try:
    # Read scripts.
    initCode = open( sotScriptsLocation + "appli.py", "r").read().split("\n")
    transitionCode = ("s()", )

    if not simulation:
        startRealRobot()

    rospy.loginfo("waiting for run_command")
    rospy.wait_for_service("run_command")
    rospy.loginfo("...ok")

    # Create clients.
    runCommandClient = rospy.ServiceProxy('run_command', RunCommand)
    runCommandStartDynamicGraph = rospy.ServiceProxy(
        'start_dynamic_graph', Empty)

    launchScript(initCode,'initialization')

    rospy.loginfo("Start the controller")
    try:
        runCommandStartDynamicGraph()
    except:
        rospy.loginfo("Error while starting the Dynamic Graph. Catched and continue.")
        raw_input("Catch an error while starting the dg. Check if you want to continue.")
    rospy.loginfo("...done")

    while True:
        launchScript(transitionCode,'next stage')
 
except rospy.ServiceException, e:
    rospy.logerr("Service call failed: %s" % e)

